name: Fitness Food APK

on:
  push:
    tags: [ "*" ]

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build Release APK
      run: ./gradlew assembleRelease
    - name: Publish APK
      uses: alsrb968/action-release-apk@master
      env:
        GITHUB_TOKEN: ${{ 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 }}
        APP_FOLDER: fitness-food-app-part1
